name: Build-And-Test
run-name: ${{ github.actor }} is building and testing the Backend

on:
    push:
        branches: [ dev ]
    pull_request:
        branches: [ dev ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x, 18.x, 20.x]

        steps:
            - run: echo "now building & testing the app"
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              working-directory: ./backend
              run: npm ci
            - name: Build node app
              working-directory: ./backend
              run: npm run build
            - name: Run tests
              working-directory: ./backend
              run: echo "running test"

    push-to-main:
        needs: build
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
                token: ${{ secrets.GITHUB_TOKEN }}
            - name: Push to main
              run: |
                git config user.name github-actions[bot]
                git config user.email github-actions[bot]@users.noreply.github.com
                git checkout main
                git merge origin/dev
                git push origin main
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}